### ISSUE TITLE
[BUG] run_docker.sh does not forward container port

### ISSUE THREAD

**Issue by gotiniens** [fgebhart/workoutizer#157]
**Describe the bug**
The default run_docker script does not provide for forwarding the port the webserver is listening to. WHen manually adding `-p 8000:8000` to `run_dokcer.sh` . You still wont see the web-interface because the webserver is specifically listening on 127.0.0.1 which is not used for forwarding.

**To Reproduce**
1. Run `run_docker.sh`
2. Type `wkz init`
3. Type `wkz run`
4. In your browser go to http://localhost:8000
5. See an Connection Refused Error

**Expected behavior**
After starting the docker image, and browsing to http://localhost:8000 with my browser I would expect to see the workoutizer web interface

**Environment:**
 - OS: Docker 19.03 on Ubuntu 21.04
 - Browser: Chrome
 - Workoutizer Version latest from git

**Additional context**
In my Forked repo I have an fix for this problem: https://github.com/gotiniens/workoutizer/commit/191b7bf4458686131b0f52823589ee3507e2f4c7

This fixes the problem for me, but this can break your workflow.

**Comment by fgebhart** [comment]
Thanks for reporting. I am able to reproduce this issue.

Just for context: I'm using VSCode together with the "remote containers" extension when developing workoutizer. This workflow uses the same underlying `Dockerfile` - but not the `run_docker.sh` script. Whenever I hit `wkz run` and click on the suggested http://127.0.0.1:8000/ url, VSCode magically routes my browser to http://127.0.0.1:49653/ which successfully shows the expected workoutizer UI.

Will check whether your suggested fix conflicts with my workflow.

**Comment by fgebhart** [comment]
Seems like with VSCode I still requires that check for the `WKZ_ENV` env var. However, together with your changes to the `run_docker.sh` script (adding the port forwarding) and changing the url to `0.0.0.0:8000` in `workoutizer.cli.run` I managed to get both worlds working:

```python
def run(url):
    if not url:
        if os.getenv("WKZ_ENV") == "devel":
            url = "0.0.0.0:8000"    # <- this got changed
        else:
            url = f"{get_local_ip_address()}:8000"
...
```

Could you verify that this approach also works with your workflow? If yes - happy to receive a PR 🙂

**Comment by gotiniens** [comment]
I considerd the solution you proposed, but I decided it was redundant for my workflow. To be sure I tested it and it seems to be working for my workflow, so I'm preparing an PR.
