### ISSUE TITLE
[ENH] Officially support Python 3.7 and run on Raspberry Pi (ARM) 

### ISSUE THREAD

**Issue by fgebhart** [fgebhart/workoutizer#162]
Since a convenient way of operating workoutizer in a local network is running it on a Raspberry Pi, it would be great if Python3.7 would be fully supported.

This includes:

- [x] a successful Python3.7 CI pipeline
- [x] sportgems needs to be cross compiles for Python3.7 on armv7 architecture - [done](https://fgebhart.github.io/sportgems/changelog.html#060-2021-06-19)
- [x] CI pipeline to test the installation of workoutizer on arm

**Comment by fgebhart** [comment]
Reopening, since it first has to be verified if installing workoutizer on Raspberry Pi is as easy as `pip install workoutizer`. If not, the instructions readme needs to be updated.

**Comment by gotiniens** [comment]
I was able to install workoutizer with `pip install -vvv workoutizer==0.20.0 --no-cache` But I needed to define the version.

Maybe I was running in some caching issue?

Because I did not have an running workoutizer instance, I threw away my venv and tried again.

```
pi@raspberrypi:~$ virtualenv -p python3 venv && source venv/bin/activate 
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pi/venv/bin/python3
Also creating executable in /home/pi/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
(venv) pi@raspberrypi:~$ pip install workoutizer
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting workoutizer
  Downloading https://www.piwheels.org/simple/workoutizer/workoutizer-0.20.0-py3-none-any.whl (943 kB)
```

That seems to be working! I will try following the readme.md and report further findings in #159

**Comment by fgebhart** [comment]
Thanks a lot for testing this @gotiniens! I also assume you first encountered caching issues.

I also tested the installation on a Raspberry Pi 3B (Buster) and it also successfully installed workoutizer v0.20.0. Therefore I would consider this issue as fixed.
