### ISSUE TITLE
[BUG] Block device not settled yet when mount triggerd by wkz_mount.service

### ISSUE THREAD

**Issue by gotiniens** [fgebhart/workoutizer#192]
**Describe the bug**
When plugging in my Garmin device, I get the following error:
```
Jul 25 21:01:28 raspberrypi wkz[560]: 07-25 22:01:28 - ERROR - wkz.api - could not mount device: cannot unpack non-iterable NoneType object
Jul 25 21:01:28 raspberrypi wkz[560]: Traceback (most recent call last):
Jul 25 21:01:28 raspberrypi wkz[560]:   File "/home/pi/venv/lib/python3.7/site-packages/wkz/api.py", line 18, in mount_device_endpoint
Jul 25 21:01:28 raspberrypi wkz[560]:     mount_path = try_to_mount_device()
Jul 25 21:01:28 raspberrypi wkz[560]:   File "/home/pi/venv/lib/python3.7/site-packages/wkz/file_helper/fit_collector.py", line 93, in try_to_mount_device
Jul 25 21:01:28 raspberrypi wkz[560]:     (type, path) = _find_device_type(bus, dev)
Jul 25 21:01:28 raspberrypi wkz[560]: TypeError: cannot unpack non-iterable NoneType object
Jul 25 21:01:28 raspberrypi wkz[560]: 07-25 22:01:28 - ERROR - django.request - Internal Server Error: /mount-device/
```
Although this error should be handled better(I will take care of this), this is also caused by my block device not ready yet to be mounted when the wkz_mount.service is triggered by udev.

After some troubleshooting I check the output of the `udevadm monitor` command
```
KERNEL[877.854533] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1 (usb)
KERNEL[877.858957] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0 (usb)
KERNEL[877.859569] add      /devices/virtual/workqueue/scsi_tmf_0 (workqueue)
KERNEL[877.862380] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0 (scsi)
KERNEL[877.862451] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/scsi_host/host0 (scsi_host)
KERNEL[877.862533] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0 (usb)
KERNEL[877.862648] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1 (usb)
UDEV  [877.865922] add      /devices/virtual/workqueue/scsi_tmf_0 (workqueue)
UDEV  [877.883068] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1 (usb)
UDEV  [877.884524] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0 (usb)
UDEV  [877.888102] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0 (scsi)
UDEV  [877.891724] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/scsi_host/host0 (scsi_host)
UDEV  [877.895082] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0 (usb)
UDEV  [877.907580] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1 (usb)
KERNEL[878.872297] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0 (scsi)
KERNEL[878.872376] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
KERNEL[878.872429] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0 (scsi_device)
KERNEL[878.872504] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_generic/sg0 (scsi_generic)
KERNEL[878.872579] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0 (bsg)
KERNEL[878.872806] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0 (scsi_disk)
UDEV  [878.876385] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0 (scsi)
KERNEL[878.876480] change   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
UDEV  [878.880500] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
UDEV  [878.885594] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0 (scsi_device)
UDEV  [878.887239] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_generic/sg0 (scsi_generic)
UDEV  [878.888806] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/scsi_disk/0:0:0:0 (scsi_disk)
UDEV  [878.890731] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0 (bsg)
UDEV  [878.894677] change   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
KERNEL[878.930324] add      /devices/virtual/bdi/8:0 (bdi)
UDEV  [878.931658] add      /devices/virtual/bdi/8:0 (bdi)
KERNEL[879.007785] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
KERNEL[879.010554] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
UDEV  [886.931941] add      /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
UDEV  [886.936138] bind     /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/host0/target0:0:0/0:0:0:0 (scsi)
```

You see that first the USB subsystem (the last field between parenthesis) is triggered, after a while SCSI subsystem and the last subsystem is the block subsystem.

So I changed the udev rule to trigger on the block subsystem instead of the USB subsystem like:
```
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="091e", ATTRS{idProduct}=="26e5", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount"
```
This works!

But this change could break for your device, So before I create an pull request with this change I would like to ask you for the output of `udevadm monitor` when plugging in your device.

**Comment by fgebhart** [comment]
The output of `udevadm monitor` when connecting my device is:

```
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[2686.181470] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2686.181760] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
KERNEL[2686.181902] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
KERNEL[2686.182997] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0 (tty)
KERNEL[2686.183212] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
KERNEL[2686.183455] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
KERNEL[2686.183829] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2686.283946] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2686.289732] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
UDEV  [2686.293948] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
UDEV  [2686.314605] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0 (tty)
UDEV  [2686.326455] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
UDEV  [2686.332443] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
UDEV  [2686.363734] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2734.385306] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0 (tty)
KERNEL[2734.385441] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
KERNEL[2734.385521] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
KERNEL[2734.385622] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
KERNEL[2734.385755] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
KERNEL[2734.386339] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2734.386633] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2734.391911] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0/tty/ttyUSB0 (tty)
UDEV  [2734.395718] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
UDEV  [2734.398091] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB0 (usb-serial)
UDEV  [2734.401625] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
UDEV  [2734.404066] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
UDEV  [2734.407728] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2734.410088] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2736.351473] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2736.355224] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
KERNEL[2736.355540] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2736.369472] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
UDEV  [2736.386060] add      /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0 (usb)
UDEV  [2736.407452] bind     /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4 (usb)
KERNEL[2737.153316] add      /devices/virtual/misc/fuse (misc)
KERNEL[2737.153508] add      /module/fuse (module)
UDEV  [2737.158365] add      /devices/virtual/misc/fuse (misc)
UDEV  [2737.161339] add      /module/fuse (module)
KERNEL[2737.172145] add      /devices/virtual/bdi/0:38 (bdi)
UDEV  [2737.175476] add      /devices/virtual/bdi/0:38 (bdi)
```

I also tried mounting my device with `SUBSYSTEM=="block"`, which unfortunately does not work.

A combined way would probably be best. I tried `SUBSYSTEM=="usb,block"`, which also doesn't work. But I'm for sure not an udev rules expert.

As a plan b we could add some instructions e.g. using `udevadm monitor` to the `setup/readme.md` file to figure out the subsystem type and modify the rule file accordingly. But let's try to first find a combined way, which works for both `usb` and `block`.

(btw, just realized the link to the RPI setup instructions points to the file on `master` branch instead of `main` - will fix this in a moment)

**Comment by fgebhart** [comment]
quick update:

I tried the following approaches:
```
ACTION=="add", SUBSYSTEM=="usb,block", ...
```
```
ACTION=="add", SUBSYSTEMS=="usb", SUBSYSTEM=="block", ...
```
```
ACTION=="add", SUBSYSTEM=="usb", SUBSYSTEM+="block", ...
```
unfortunately without success. Will keep on trying other things. Let me know if you have another idea.

**Comment by gotiniens** [comment]
I found that UDEV supports the GOTO, and LABEL parameters. I think that's the key to our problem.

I tried it with this udev rule, and it seems to work, can you test it for your device?

```
ATTRS{ID_MTP_DEVICE}="1", GOTO="mtp_rule"
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="091e", ATTRS{idProduct}=="26e5", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"

LABEL="mtp_rule"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="091e", ATTRS{idProduct}=="26e5", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"

LABEL="end"
```
the first rule works as an if statement, if the device has the ID_MTP_DEVICE attribute goto label mtp_rule. I could not find an similar value for the block device,

**Comment by fgebhart** [comment]
This approach also works for me 👍

I'm fine with adding this updated udev rule to the RPI instructions readme, even though it comes with a little drawback in ease of use. Now a new user would have to either know the subsystem of the device or modify the value of `idVendor` and `idProduct` twice, which may be overlooked and could cause problems.

I'm starting to think about a potential way of automating this, e.g. by implementing an additional cli option. Something like `wkz prepare-mount` or `wkz add-udev-rule`, which accepts the `idVendor` and `idProduct` (or reads it from a file) and generates the desired udev rule and stores it into the required location. I once had a similar command, I think it was `wkz prepare-rpi`, which did similar things, but used ansible under the hood and was totally over engineered and hard to maintain. I removed it in favor of the old-school step-by-step guide, which we have now. I'm curious about your opinion on the current installation process. Is it too complicated or too much effort? I assumed people working on Raspbeery Pis are usually fine with creating a few files by hand.

Anyway, happy to receive a PR with your suggested changes. Let's keep the automation thing for future work.

**Comment by gotiniens** [comment]
> This approach also works for me 
> 
> I'm fine with adding this updated udev rule to the RPI instructions readme, even though it comes with a little drawback in ease of use. Now a new user would have to either know the subsystem of the device or modify the value of `idVendor` and `idProduct` twice, which may be overlooked and could cause problems.
> 

Yes I was also thinking about this, I tried to find an solution, and I came up with this:
```
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="091e", ATTRS{idProduct}=="26e5", GOTO="device_found"

LABEL="device_found"
ATTRS{ID_MTP_DEVICE}="1", GOTO="mtp_rule"
TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"


LABEL="mtp_rule"
TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"

LABEL="end"
```
Too bad this does not work correctly :disappointed: 

Removing the `ATTRS{idProduct}` should trigger the rule for all garmin devices. and hardcoding the `ATTRS{idVendor}=="091e"` will remove the need for the user to configure the ID's itself. `091e` looks like the [only vendorID from Garmin](https://usb-ids.gowdy.us/usb.ids). So that should work for all currently known supported devices.

> I'm starting to think about a potential way of automating this, e.g. by implementing an additional cli option. Something like `wkz prepare-mount` or `wkz add-udev-rule`, which accepts the `idVendor` and `idProduct` (or reads it from a file) and generates the desired udev rule and stores it into the required location. I once had a similar command, I think it was `wkz prepare-rpi`, which did similar things, but used ansible under the hood and was totally over engineered and hard to maintain. I removed it in favor of the old-school step-by-step guide, which we have now. I'm curious about your opinion on the current installation process. Is it too complicated or too much effort? I assumed people working on Raspbeery Pis are usually fine with creating a few files by hand.
> 
I think an mostly automatic install would be good for adoption of the project. A lot of Raspberry projects have an single line install, [like pi-hole](https://github.com/pi-hole/pi-hole/#one-step-automated-install). 

Ansible is very very suitable for this I think, Can you give a link to the (old) code?

> Anyway, happy to receive a PR with your suggested changes. Let's keep the automation thing for future work.

Coming up.

**Comment by fgebhart** [comment]
> Removing the ATTRS{idProduct} should trigger the rule for all garmin devices. and hardcoding the ATTRS{idVendor}=="091e" will remove the need for the user to configure the ID's itself. 091e looks like the only vendorID from Garmin. So that should work for all currently known supported devices.

This seems like a good idea to me. Couldn't we just use something like this generic rule in that case:
```
ATTRS{ID_MTP_DEVICE}="1", GOTO="mtp_rule"
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="091e", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"

LABEL="mtp_rule"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="091e", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount", GOTO="end"

LABEL="end"
```
Which should be able to mount all garmin block and mtp devices? In this case users won't even have to find out the ids of their device at all. (Didn't test the above rule yet).

> Ansible is very very suitable for this I think, Can you give a link to the (old) code?

[Here](https://github.com/fgebhart/workoutizer/blob/v0.10.0/workoutizer/__main__.py#L44) is the old `setup_rpi` cli command using ansible. If I remember it correctly, this approach worked, but having ansible in the dependencies increases the installation time of workoutizer quite a bit and caused loads of dependabot version bump PRs because of security issues. Additionally it was hard to maintain in the sense of adding / improving features. Thus I consider it to be over-engineered, since all it would need to do is templating some files (using e.g. `jinja` - which comes with bokeh) and copying them to some location.

Because of this I would be much in favor of solving this with plain python and packages which are already part of workoutizer.  

Small side note: One potential challenge I see could be the fact that super user privileges would be required when saving files to `/etc/...`. Because when running `sudo wkz --version`, a different `PATH` is used and thus the `wkz` cli is not found: `sudo: wkz: command not found`. So maybe an installation script similar to what pi-hole has could circumvent this.

**Comment by gotiniens** [comment]
The above mentioned udev file with the labels, seemed to still be triggering too early when plugging in my device. With the rest of the discussion I came up with the following rules:
```
ACTION=="add", SUBSYSTEM=="block", ATTRS{idVendor}=="091e", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="091e", ATTRS{ID_MTP_DEVICE}="1", TAG+="systemd", ENV{SYSTEMD_WANTS}="wkz_mount"
```

This should have come up earlier, It is a lot easier to understand :smile:. With these rules order should not matter.
