### ISSUE TITLE
FRONTEND: Collapse button in sidebar does not properly adapt its position when zooming in/out

### ISSUE THREAD

**Issue by fgebhart** [fgebhart/workoutizer#40]
When zooming in / out the position of the "collapse" button in the (left) sidebar is not adjusting its position properly. Its position should be fixed to the bottom of the page. See the attached images:

Here the position of the collapse button is correct:
<img width="1440" alt="Screenshot 2020-12-23 at 10 06 51" src="https://user-images.githubusercontent.com/16943048/102979869-f952b700-4506-11eb-93cd-bd62fb69b34d.png">

When zooming out, the position of the button moves up instead of staying at the bottom of the page:
<img width="1440" alt="Screenshot 2020-12-23 at 10 07 07" src="https://user-images.githubusercontent.com/16943048/102979888-01125b80-4507-11eb-839f-e8bbd6bcba26.png">

When refreshing the  page in the new zoom level, the position of the collapse button again correct. However, it would be nice to have the position fixed and adapt responsive properly when zooming in and out.

**Comment by lucasace** [comment]
I'd like to take this up
If you could help me with the starting point, it would be nice

**Comment by fgebhart** [comment]
Sure thing 👍 

In general all html templates are located in `wizer/templates/`. Inside the `lib/` folder you find generic templates which are used for generic things like navbar, errors and the left sidebar. Have a look at the `sidebar.html` file:

* [In line 47](https://github.com/fgebhart/workoutizer/blob/master/wizer/templates/lib/sidebar.html#L47) the "collapse" button is defined
* Using a bit of javascript I managed to open and close the sidebar. This happens [in line 54 and below](https://github.com/fgebhart/workoutizer/blob/master/wizer/templates/lib/sidebar.html#L54).
* [Here](https://github.com/fgebhart/workoutizer/blob/master/wizer/templates/lib/sidebar.html#L77) you can see that the position of the "collapse" button is determined by multiplying the row height times the row number and subtracting it from the sidebar height.

Nowadays I would consider the implementation of the last bullet point a bit hacky and I am sure there is a simpler solution to this which also fixes this issue.

A potential solution could be to determine the position of the button by setting it relative to the bottom of the page and not by counting the vertical height from the top.

On a more general note: (As you might realize) I am more the backend guy and my frontend skills are pretty basic. So feel free to adjust also other frontend related things while touching the code base 😉 

Let me know if you have any other questions.

**Comment by lucasace** [comment]
Thank you !
I'll get started on this

**Comment by fgebhart** [comment]
@lucasace I have to admit that this part of the code base was not the easiest to wrap your head around 🙈  Check out the diff of the above linked PR if you want. It turned out using buttons instead of the table approach and the following attribute did the trick:
```css
position: fixed;
bottom: 0px;
```

**Comment by lucasace** [comment]
Heyy, I am really sorry, I know its not the best open-source behavior 😓 , I was busy with projects of my own and didn't really get much time to look at it, I had done a few things but didnt manage to get the result. 
Wont happen again 😄

**Comment by fgebhart** [comment]
no worries! :)
