### ISSUE TITLE
let sidebar disappear when zoomed in a lot or on small devices

### ISSUE THREAD

**Issue by fgebhart** [fgebhart/workoutizer#5]
make it either responsive or simply only display on large screens: https://stackoverflow.com/questions/48358208/how-to-show-text-only-on-mobile-with-css

**Comment by pa3kDaWae** [comment]
Hi, may i work on this issue? Could you assign it to me if yes?

**Comment by fgebhart** [comment]
Sure! I appreciate your commitment :)
This issue focuses on the *right* sidebar (sidenav) which currently is included in the `dashboard.html`: https://github.com/fgebhart/workoutizer/blob/master/wizer/templates/dashboard.html

Let me know if you need any help or more input. Since I'm not too experienced with frontend development, feel free to adapt also other parts of the code if it comes with an improvement of any kind.

**Comment by pa3kDaWae** [comment]
Thanks for the additional info, will keep you updated! :)
