### ISSUE TITLE
replace all os.path references with pathlib 

### ISSUE THREAD

**Issue by fgebhart** [fgebhart/workoutizer#53]
This currently seems to block workoutizer from supporting windows.
- [ ] replace `os.path` with `pathlib`

**Comment by polyvertex** [comment]
How so? `os.path` is as Windows-compatible as it can be.

However I noticed improper file path manipulation in project's code, tests included. Typically `path.split("/")` or `os.path.join(somedir, "foo/bar/")`...

**Comment by fgebhart** [comment]
You are of course right, `os.path` is totally windows compatible.

When I wrote this issue, I simply added a `windows-latest` to the [matrix test ](https://github.com/fgebhart/workoutizer/blob/main/.github/workflows/matrix_test.yml#L38) and realized a bunch of tests were failing because of improper paths.

I thought it would be good to streamline the usage of path handling methods to just use either of both options and since I preferred `pathlib` I came up with this issue.

Your approach seems also to be totally valid 👍

**Comment by polyvertex** [comment]
> I simply added a windows-latest to the matrix test and realized a bunch of tests were failing because of improper paths.

Path manipulations that were fixed in #209 is a step towards workoutizer's Windows compat I guess 😀

> I thought it would be good to streamline the usage of path handling methods to just use either of both options and since I preferred pathlib I came up with this issue.

`pathlib` is appealing but its use might be overkill in some places. Typically when only a call to `os.path.basename` would do for instance. So that you do not need to instantiate a `PurePath` object (or derived) for a single path manipulation.

**Comment by fgebhart** [comment]
Closing this issue, since the original intend was to resolve improper path manipulation which blocked the windows compatibility. See https://github.com/fgebhart/workoutizer/issues/210 for ongoing migrations efforts.
