### ISSUE TITLE
FRONTEND: Add Datetime Picker for adding / editing Acitivites 

### ISSUE THREAD

**Issue by fgebhart** [fgebhart/workoutizer#8]
Add some fancy datetime picker. Could be either a js widget or a django tool, similar to what is in place for the color picker.

For reference:
* This is how the django-colorfield is implemented: https://github.com/fgebhart/workoutizer/blob/master/wizer/models.py#L21
* This template contains the html form and the input field for the date (which actually is datetime): https://github.com/fgebhart/workoutizer/blob/master/wizer/templates/activity/add_activity.html#L23

**Comment by Christiankoo** [comment]
Can i take this issue, please?

**Comment by fgebhart** [comment]
Sure thing! Contributions are welcome. Let me know if you need more input.

**Comment by fgebhart** [comment]
Hey @Christiankoo do you need help with this?

**Comment by fgebhart** [comment]
potential approaches for solving this:
* use the datetime picker widget of django admin: https://stackoverflow.com/a/38916/5384702
* use a custom javascript widget, e.g. one of: https://simpleisbetterthancomplex.com/tutorial/2019/01/03/how-to-use-date-picker-with-django.html
