### ISSUE TITLE
Add import/copy command to workoutizer

### ISSUE THREAD

**Issue by bintzandt** [fgebhart/workoutizer#94]
As first signaled in #90, the current flow of workoutizer expects that the device is unmounted before the files are copied. In some cases the OS automatically mounts the device (or the user uses a different way to mount the device).

In order to let the user profit from the automatic import process, it would be nice to add a command / route to workoutizer that only copies the files from the `device_path` + `activity_folder_path`.

This gives the user the flexibility to use a different mounting strategy in combination with either manually running `wkz import` or automatically triggering the command (maybe a cron job or something similar).

I think this issue would "fix" point 2 and 3 of https://github.com/fgebhart/workoutizer/issues/90#issuecomment-789191614.

**Comment by fgebhart** [comment]
Thanks for creating this issue. I guess I have been running workoutizer for too long on my Raspberry Pi and became blind to what happens on other systems. The RPI unfortunately does not auto mount garmin devices.

I think the best approach to solve this issue would to be (similar to what you have suggested) to remove the file copying from the `mount_device_endpoint` endpoint. Workoutizer will only mount your device if you configure it to do so, like currently described in [setup](https://github.com/fgebhart/workoutizer/tree/master/setup). The copying, however, should happen irrespective of whether workoutizer is running on a Raspberry Pi or any other machine.

Currently I could image to implement another watchdog to monitor the path in which the device is expected to be mounted. Once the device gets mounted (irrespective of how it got mounted) the watchdog would trigger the copying which would copy the files from the device to the target location configured in `settings.path_to_trace_dir`. And from here everything behaves like before (watchdog triggers import of activity fit files).

I will try to make the solution as generic as possible. For that it would be helpful if you could share the following two paths:
On Raspberry Pi 3B Raspbian 10 (buster):
1. Path to the activity folder (which contains the `.fit` activity files) once mounted: `/run/user/1000/gvfs/mtp\:host\=091e_4b48_0000c4fa0516/Primary/GARMIN/Activity/`
2. The biggest fraction of the above path when device is not mounted: `/run/user/1000/gvfs/`

**Comment by fgebhart** [comment]
Just double checked, the paths are exactly the same on Linux Mint 20 (Ulyana). So I would assume this to be the case for most debian based linux distros (e.g. Ubuntu, Raspbian).
